# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cargo_monitor_protos/topics_graph.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cargo_monitor_protos/topics_graph.proto',
  package='cargo.common',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\'cargo_monitor_protos/topics_graph.proto\x12\x0c\x63\x61rgo.common\"Q\n\tTopicEdge\x12\x0c\n\x04node\x18\x01 \x01(\t\x12\r\n\x05topic\x18\x02 \x01(\t\x12\x12\n\ninput_node\x18\x03 \x01(\t\x12\x13\n\x0binput_topic\x18\x04 \x01(\t\"H\n\nTopicGraph\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12%\n\x04\x65\x64ge\x18\x02 \x03(\x0b\x32\x17.cargo.common.TopicEdgeb\x06proto3'
)




_TOPICEDGE = _descriptor.Descriptor(
  name='TopicEdge',
  full_name='cargo.common.TopicEdge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='node', full_name='cargo.common.TopicEdge.node', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='topic', full_name='cargo.common.TopicEdge.topic', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='input_node', full_name='cargo.common.TopicEdge.input_node', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='input_topic', full_name='cargo.common.TopicEdge.input_topic', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=138,
)


_TOPICGRAPH = _descriptor.Descriptor(
  name='TopicGraph',
  full_name='cargo.common.TopicGraph',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='cargo.common.TopicGraph.description', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='edge', full_name='cargo.common.TopicGraph.edge', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=212,
)

_TOPICGRAPH.fields_by_name['edge'].message_type = _TOPICEDGE
DESCRIPTOR.message_types_by_name['TopicEdge'] = _TOPICEDGE
DESCRIPTOR.message_types_by_name['TopicGraph'] = _TOPICGRAPH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TopicEdge = _reflection.GeneratedProtocolMessageType('TopicEdge', (_message.Message,), {
  'DESCRIPTOR' : _TOPICEDGE,
  '__module__' : 'cargo_monitor_protos.topics_graph_pb2'
  # @@protoc_insertion_point(class_scope:cargo.common.TopicEdge)
  })
_sym_db.RegisterMessage(TopicEdge)

TopicGraph = _reflection.GeneratedProtocolMessageType('TopicGraph', (_message.Message,), {
  'DESCRIPTOR' : _TOPICGRAPH,
  '__module__' : 'cargo_monitor_protos.topics_graph_pb2'
  # @@protoc_insertion_point(class_scope:cargo.common.TopicGraph)
  })
_sym_db.RegisterMessage(TopicGraph)


# @@protoc_insertion_point(module_scope)
