# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cargo_monitor_protos/topic_status.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from common_protos import header_pb2 as common__protos_dot_header__pb2
from common_protos import status_pb2 as common__protos_dot_status__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cargo_monitor_protos/topic_status.proto',
  package='cargo.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\'cargo_monitor_protos/topic_status.proto\x12\x0b\x63\x61rgo.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1a\x63ommon_protos/header.proto\x1a\x1a\x63ommon_protos/status.proto\"d\n\x0fTopicStatusInfo\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.cargo.common.Header\x12+\n\x0bstatus_list\x18\x64 \x03(\x0b\x32\x16.cargo.common.StatusPbb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,common__protos_dot_header__pb2.DESCRIPTOR,common__protos_dot_status__pb2.DESCRIPTOR,])




_TOPICSTATUSINFO = _descriptor.Descriptor(
  name='TopicStatusInfo',
  full_name='cargo.proto.TopicStatusInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='cargo.proto.TopicStatusInfo.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status_list', full_name='cargo.proto.TopicStatusInfo.status_list', index=1,
      number=100, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=244,
)

_TOPICSTATUSINFO.fields_by_name['header'].message_type = common__protos_dot_header__pb2._HEADER
_TOPICSTATUSINFO.fields_by_name['status_list'].message_type = common__protos_dot_status__pb2._STATUSPB
DESCRIPTOR.message_types_by_name['TopicStatusInfo'] = _TOPICSTATUSINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TopicStatusInfo = _reflection.GeneratedProtocolMessageType('TopicStatusInfo', (_message.Message,), {
  'DESCRIPTOR' : _TOPICSTATUSINFO,
  '__module__' : 'cargo_monitor_protos.topic_status_pb2'
  # @@protoc_insertion_point(class_scope:cargo.proto.TopicStatusInfo)
  })
_sym_db.RegisterMessage(TopicStatusInfo)


# @@protoc_insertion_point(module_scope)
