# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cmw_mgr_protos/cmw_mgr.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cmw_mgr_protos/cmw_mgr.proto',
  package='cargo.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1c\x63mw_mgr_protos/cmw_mgr.proto\x12\x0b\x63\x61rgo.proto\"1\n\x08TopicCfg\x12\x12\n\ntopic_name\x18\x01 \x01(\t\x12\x11\n\tdata_type\x18\x02 \x01(\t\"J\n\tCmwMgrCfg\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12(\n\ttopic_cfg\x18\x02 \x03(\x0b\x32\x15.cargo.proto.TopicCfgb\x06proto3'
)




_TOPICCFG = _descriptor.Descriptor(
  name='TopicCfg',
  full_name='cargo.proto.TopicCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic_name', full_name='cargo.proto.TopicCfg.topic_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_type', full_name='cargo.proto.TopicCfg.data_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=94,
)


_CMWMGRCFG = _descriptor.Descriptor(
  name='CmwMgrCfg',
  full_name='cargo.proto.CmwMgrCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='cargo.proto.CmwMgrCfg.description', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='topic_cfg', full_name='cargo.proto.CmwMgrCfg.topic_cfg', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=170,
)

_CMWMGRCFG.fields_by_name['topic_cfg'].message_type = _TOPICCFG
DESCRIPTOR.message_types_by_name['TopicCfg'] = _TOPICCFG
DESCRIPTOR.message_types_by_name['CmwMgrCfg'] = _CMWMGRCFG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TopicCfg = _reflection.GeneratedProtocolMessageType('TopicCfg', (_message.Message,), {
  'DESCRIPTOR' : _TOPICCFG,
  '__module__' : 'cmw_mgr_protos.cmw_mgr_pb2'
  # @@protoc_insertion_point(class_scope:cargo.proto.TopicCfg)
  })
_sym_db.RegisterMessage(TopicCfg)

CmwMgrCfg = _reflection.GeneratedProtocolMessageType('CmwMgrCfg', (_message.Message,), {
  'DESCRIPTOR' : _CMWMGRCFG,
  '__module__' : 'cmw_mgr_protos.cmw_mgr_pb2'
  # @@protoc_insertion_point(class_scope:cargo.proto.CmwMgrCfg)
  })
_sym_db.RegisterMessage(CmwMgrCfg)


# @@protoc_insertion_point(module_scope)
