# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service_protos/log_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='service_protos/log_service.proto',
  package='service_manager',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n service_protos/log_service.proto\x12\x0fservice_manager\x1a\x1bgoogle/protobuf/empty.proto\"\x1d\n\nLogContent\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"\x1f\n\x0bLogFileName\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t2R\n\nLogService\x12\x44\n\x03Log\x12\x1c.service_manager.LogFileName\x1a\x1b.service_manager.LogContent\"\x00\x30\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_LOGCONTENT = _descriptor.Descriptor(
  name='LogContent',
  full_name='service_manager.LogContent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='service_manager.LogContent.content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=111,
)


_LOGFILENAME = _descriptor.Descriptor(
  name='LogFileName',
  full_name='service_manager.LogFileName',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='service_manager.LogFileName.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=144,
)

DESCRIPTOR.message_types_by_name['LogContent'] = _LOGCONTENT
DESCRIPTOR.message_types_by_name['LogFileName'] = _LOGFILENAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LogContent = _reflection.GeneratedProtocolMessageType('LogContent', (_message.Message,), {
  'DESCRIPTOR' : _LOGCONTENT,
  '__module__' : 'service_protos.log_service_pb2'
  # @@protoc_insertion_point(class_scope:service_manager.LogContent)
  })
_sym_db.RegisterMessage(LogContent)

LogFileName = _reflection.GeneratedProtocolMessageType('LogFileName', (_message.Message,), {
  'DESCRIPTOR' : _LOGFILENAME,
  '__module__' : 'service_protos.log_service_pb2'
  # @@protoc_insertion_point(class_scope:service_manager.LogFileName)
  })
_sym_db.RegisterMessage(LogFileName)



_LOGSERVICE = _descriptor.ServiceDescriptor(
  name='LogService',
  full_name='service_manager.LogService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=146,
  serialized_end=228,
  methods=[
  _descriptor.MethodDescriptor(
    name='Log',
    full_name='service_manager.LogService.Log',
    index=0,
    containing_service=None,
    input_type=_LOGFILENAME,
    output_type=_LOGCONTENT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOGSERVICE)

DESCRIPTOR.services_by_name['LogService'] = _LOGSERVICE

# @@protoc_insertion_point(module_scope)
