# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from service_protos import log_service_pb2 as service__protos_dot_log__service__pb2


class LogServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Log = channel.unary_stream(
                '/service_manager.LogService/Log',
                request_serializer=service__protos_dot_log__service__pb2.LogFileName.SerializeToString,
                response_deserializer=service__protos_dot_log__service__pb2.LogContent.FromString,
                )


class LogServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Log(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Log': grpc.unary_stream_rpc_method_handler(
                    servicer.Log,
                    request_deserializer=service__protos_dot_log__service__pb2.LogFileName.FromString,
                    response_serializer=service__protos_dot_log__service__pb2.LogContent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'service_manager.LogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LogService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Log(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/service_manager.LogService/Log',
            service__protos_dot_log__service__pb2.LogFileName.SerializeToString,
            service__protos_dot_log__service__pb2.LogContent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
