# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from service_protos import module_service_pb2 as service__protos_dot_module__service__pb2


class ModuleServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecordModuleInfo = channel.unary_unary(
                '/service_manager.ModuleService/RecordModuleInfo',
                request_serializer=service__protos_dot_module__service__pb2.ModuleInfo.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetModuleInfoCollection = channel.unary_unary(
                '/service_manager.ModuleService/GetModuleInfoCollection',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=service__protos_dot_module__service__pb2.ModuleInfoCollection.FromString,
                )


class ModuleServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RecordModuleInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModuleInfoCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModuleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecordModuleInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordModuleInfo,
                    request_deserializer=service__protos_dot_module__service__pb2.ModuleInfo.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetModuleInfoCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModuleInfoCollection,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=service__protos_dot_module__service__pb2.ModuleInfoCollection.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'service_manager.ModuleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ModuleService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecordModuleInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/service_manager.ModuleService/RecordModuleInfo',
            service__protos_dot_module__service__pb2.ModuleInfo.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetModuleInfoCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/service_manager.ModuleService/GetModuleInfoCollection',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            service__protos_dot_module__service__pb2.ModuleInfoCollection.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
