# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service_protos/recorder_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='service_protos/recorder_service.proto',
  package='service_manager',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n%service_protos/recorder_service.proto\x12\x0fservice_manager\x1a\x1bgoogle/protobuf/empty.proto\"\"\n\rCommonRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\"#\n\x0e\x43ommonResponse\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\")\n\x08TripInfo\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\n\n\x02id\x18\x02 \x01(\t\"M\n\x10RecordNodeStatus\x12\x0c\n\x04name\x18\x01 \x01(\t\x12+\n\x06status\x18\x02 \x01(\x0e\x32\x1b.service_manager.RecordInfo*S\n\nRecordInfo\x12\x11\n\rRECORDRUNNING\x10\x00\x12\x0e\n\nMANUALSTOP\x10\x01\x12\x12\n\x0eUNEXPECTEDSTOP\x10\x02\x12\x0e\n\nDISCONNECT\x10\x03\x32\x92\x03\n\x0fRecorderService\x12J\n\x0bStartRecord\x12\x1e.service_manager.CommonRequest\x1a\x19.service_manager.TripInfo\"\x00\x12I\n\nCreateTrip\x12\x1e.service_manager.CommonRequest\x1a\x19.service_manager.TripInfo\"\x00\x12J\n\x0bGetTripInfo\x12\x1e.service_manager.CommonRequest\x1a\x19.service_manager.TripInfo\"\x00\x12O\n\nStopRecord\x12\x1e.service_manager.CommonRequest\x1a\x1f.service_manager.CommonResponse\"\x00\x12K\n\x0cRecordStatus\x12\x16.google.protobuf.Empty\x1a!.service_manager.RecordNodeStatus\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])

_RECORDINFO = _descriptor.EnumDescriptor(
  name='RecordInfo',
  full_name='service_manager.RecordInfo',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RECORDRUNNING', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MANUALSTOP', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UNEXPECTEDSTOP', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DISCONNECT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=282,
  serialized_end=365,
)
_sym_db.RegisterEnumDescriptor(_RECORDINFO)

RecordInfo = enum_type_wrapper.EnumTypeWrapper(_RECORDINFO)
RECORDRUNNING = 0
MANUALSTOP = 1
UNEXPECTEDSTOP = 2
DISCONNECT = 3



_COMMONREQUEST = _descriptor.Descriptor(
  name='CommonRequest',
  full_name='service_manager.CommonRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='service_manager.CommonRequest.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=121,
)


_COMMONRESPONSE = _descriptor.Descriptor(
  name='CommonResponse',
  full_name='service_manager.CommonResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='service_manager.CommonResponse.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=158,
)


_TRIPINFO = _descriptor.Descriptor(
  name='TripInfo',
  full_name='service_manager.TripInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='service_manager.TripInfo.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='service_manager.TripInfo.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=201,
)


_RECORDNODESTATUS = _descriptor.Descriptor(
  name='RecordNodeStatus',
  full_name='service_manager.RecordNodeStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='service_manager.RecordNodeStatus.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='service_manager.RecordNodeStatus.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=280,
)

_RECORDNODESTATUS.fields_by_name['status'].enum_type = _RECORDINFO
DESCRIPTOR.message_types_by_name['CommonRequest'] = _COMMONREQUEST
DESCRIPTOR.message_types_by_name['CommonResponse'] = _COMMONRESPONSE
DESCRIPTOR.message_types_by_name['TripInfo'] = _TRIPINFO
DESCRIPTOR.message_types_by_name['RecordNodeStatus'] = _RECORDNODESTATUS
DESCRIPTOR.enum_types_by_name['RecordInfo'] = _RECORDINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CommonRequest = _reflection.GeneratedProtocolMessageType('CommonRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMMONREQUEST,
  '__module__' : 'service_protos.recorder_service_pb2'
  # @@protoc_insertion_point(class_scope:service_manager.CommonRequest)
  })
_sym_db.RegisterMessage(CommonRequest)

CommonResponse = _reflection.GeneratedProtocolMessageType('CommonResponse', (_message.Message,), {
  'DESCRIPTOR' : _COMMONRESPONSE,
  '__module__' : 'service_protos.recorder_service_pb2'
  # @@protoc_insertion_point(class_scope:service_manager.CommonResponse)
  })
_sym_db.RegisterMessage(CommonResponse)

TripInfo = _reflection.GeneratedProtocolMessageType('TripInfo', (_message.Message,), {
  'DESCRIPTOR' : _TRIPINFO,
  '__module__' : 'service_protos.recorder_service_pb2'
  # @@protoc_insertion_point(class_scope:service_manager.TripInfo)
  })
_sym_db.RegisterMessage(TripInfo)

RecordNodeStatus = _reflection.GeneratedProtocolMessageType('RecordNodeStatus', (_message.Message,), {
  'DESCRIPTOR' : _RECORDNODESTATUS,
  '__module__' : 'service_protos.recorder_service_pb2'
  # @@protoc_insertion_point(class_scope:service_manager.RecordNodeStatus)
  })
_sym_db.RegisterMessage(RecordNodeStatus)



_RECORDERSERVICE = _descriptor.ServiceDescriptor(
  name='RecorderService',
  full_name='service_manager.RecorderService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=368,
  serialized_end=770,
  methods=[
  _descriptor.MethodDescriptor(
    name='StartRecord',
    full_name='service_manager.RecorderService.StartRecord',
    index=0,
    containing_service=None,
    input_type=_COMMONREQUEST,
    output_type=_TRIPINFO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CreateTrip',
    full_name='service_manager.RecorderService.CreateTrip',
    index=1,
    containing_service=None,
    input_type=_COMMONREQUEST,
    output_type=_TRIPINFO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetTripInfo',
    full_name='service_manager.RecorderService.GetTripInfo',
    index=2,
    containing_service=None,
    input_type=_COMMONREQUEST,
    output_type=_TRIPINFO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StopRecord',
    full_name='service_manager.RecorderService.StopRecord',
    index=3,
    containing_service=None,
    input_type=_COMMONREQUEST,
    output_type=_COMMONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RecordStatus',
    full_name='service_manager.RecorderService.RecordStatus',
    index=4,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_RECORDNODESTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RECORDERSERVICE)

DESCRIPTOR.services_by_name['RecorderService'] = _RECORDERSERVICE

# @@protoc_insertion_point(module_scope)
