# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service_protos/recorder_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service_protos/recorder_info.proto',
  package='service_manager',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"service_protos/recorder_info.proto\x12\x0fservice_manager\"@\n\x0cRecorderInfo\x12\x16\n\x0erecorder_nodes\x18\x01 \x03(\t\x12\x18\n\x10\x63urrent_recorder\x18\x02 \x01(\tb\x06proto3'
)




_RECORDERINFO = _descriptor.Descriptor(
  name='RecorderInfo',
  full_name='service_manager.RecorderInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='recorder_nodes', full_name='service_manager.RecorderInfo.recorder_nodes', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_recorder', full_name='service_manager.RecorderInfo.current_recorder', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=119,
)

DESCRIPTOR.message_types_by_name['RecorderInfo'] = _RECORDERINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecorderInfo = _reflection.GeneratedProtocolMessageType('RecorderInfo', (_message.Message,), {
  'DESCRIPTOR' : _RECORDERINFO,
  '__module__' : 'service_protos.recorder_info_pb2'
  # @@protoc_insertion_point(class_scope:service_manager.RecorderInfo)
  })
_sym_db.RegisterMessage(RecorderInfo)


# @@protoc_insertion_point(module_scope)
