# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common_protos/input_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common_protos import header_pb2 as common__protos_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='common_protos/input_info.proto',
  package='cargo.common',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1e\x63ommon_protos/input_info.proto\x12\x0c\x63\x61rgo.common\x1a\x1a\x63ommon_protos/header.proto\"\xa2\x01\n\tInputInfo\x12\x12\n\ntopic_name\x18\x01 \x01(\t\x12$\n\x06header\x18\x02 \x01(\x0b\x32\x14.cargo.common.Header\x12\x19\n\x11recv_timestamp_ns\x18\x03 \x01(\x03\x12\x1d\n\x15\x63\x61llback_timestamp_ns\x18\x04 \x01(\x03\x12!\n\x19\x63\x61llback_end_timestamp_ns\x18\x05 \x01(\x03\"9\n\nInputInfos\x12+\n\ninput_info\x18\x01 \x03(\x0b\x32\x17.cargo.common.InputInfob\x06proto3'
  ,
  dependencies=[common__protos_dot_header__pb2.DESCRIPTOR,])




_INPUTINFO = _descriptor.Descriptor(
  name='InputInfo',
  full_name='cargo.common.InputInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic_name', full_name='cargo.common.InputInfo.topic_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='header', full_name='cargo.common.InputInfo.header', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='recv_timestamp_ns', full_name='cargo.common.InputInfo.recv_timestamp_ns', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='callback_timestamp_ns', full_name='cargo.common.InputInfo.callback_timestamp_ns', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='callback_end_timestamp_ns', full_name='cargo.common.InputInfo.callback_end_timestamp_ns', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=239,
)


_INPUTINFOS = _descriptor.Descriptor(
  name='InputInfos',
  full_name='cargo.common.InputInfos',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_info', full_name='cargo.common.InputInfos.input_info', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=298,
)

_INPUTINFO.fields_by_name['header'].message_type = common__protos_dot_header__pb2._HEADER
_INPUTINFOS.fields_by_name['input_info'].message_type = _INPUTINFO
DESCRIPTOR.message_types_by_name['InputInfo'] = _INPUTINFO
DESCRIPTOR.message_types_by_name['InputInfos'] = _INPUTINFOS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InputInfo = _reflection.GeneratedProtocolMessageType('InputInfo', (_message.Message,), {
  'DESCRIPTOR' : _INPUTINFO,
  '__module__' : 'common_protos.input_info_pb2'
  # @@protoc_insertion_point(class_scope:cargo.common.InputInfo)
  })
_sym_db.RegisterMessage(InputInfo)

InputInfos = _reflection.GeneratedProtocolMessageType('InputInfos', (_message.Message,), {
  'DESCRIPTOR' : _INPUTINFOS,
  '__module__' : 'common_protos.input_info_pb2'
  # @@protoc_insertion_point(class_scope:cargo.common.InputInfos)
  })
_sym_db.RegisterMessage(InputInfos)


# @@protoc_insertion_point(module_scope)
