# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common_protos/latency.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common_protos/latency.proto',
  package='cargo.common',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1b\x63ommon_protos/latency.proto\x12\x0c\x63\x61rgo.common\"+\n\nTaskStates\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07time_ms\x18\x02 \x01(\x01\"o\n\x0cLatencyStats\x12\x15\n\rtotal_time_ms\x18\x01 \x01(\x01\x12,\n\ntaskstates\x18\x02 \x03(\x0b\x32\x18.cargo.common.TaskStates\x12\x1a\n\x12start_timestamp_ns\x18\n \x01(\x03\x62\x06proto3'
)




_TASKSTATES = _descriptor.Descriptor(
  name='TaskStates',
  full_name='cargo.common.TaskStates',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='cargo.common.TaskStates.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_ms', full_name='cargo.common.TaskStates.time_ms', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=88,
)


_LATENCYSTATS = _descriptor.Descriptor(
  name='LatencyStats',
  full_name='cargo.common.LatencyStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='total_time_ms', full_name='cargo.common.LatencyStats.total_time_ms', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='taskstates', full_name='cargo.common.LatencyStats.taskstates', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_timestamp_ns', full_name='cargo.common.LatencyStats.start_timestamp_ns', index=2,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=201,
)

_LATENCYSTATS.fields_by_name['taskstates'].message_type = _TASKSTATES
DESCRIPTOR.message_types_by_name['TaskStates'] = _TASKSTATES
DESCRIPTOR.message_types_by_name['LatencyStats'] = _LATENCYSTATS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TaskStates = _reflection.GeneratedProtocolMessageType('TaskStates', (_message.Message,), {
  'DESCRIPTOR' : _TASKSTATES,
  '__module__' : 'common_protos.latency_pb2'
  # @@protoc_insertion_point(class_scope:cargo.common.TaskStates)
  })
_sym_db.RegisterMessage(TaskStates)

LatencyStats = _reflection.GeneratedProtocolMessageType('LatencyStats', (_message.Message,), {
  'DESCRIPTOR' : _LATENCYSTATS,
  '__module__' : 'common_protos.latency_pb2'
  # @@protoc_insertion_point(class_scope:cargo.common.LatencyStats)
  })
_sym_db.RegisterMessage(LatencyStats)


# @@protoc_insertion_point(module_scope)
